version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vehicle_tracker_db
    environment:
      POSTGRES_DB: vehicle_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vehicle_network

  redis:
    image: redis:7-alpine
    container_name: vehicle_tracker_redis
    ports:
      - "6379:6379"
    networks:
      - vehicle_network

volumes:
  postgres_data:

networks:
  vehicle_network:
    driver: bridge